# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\nai_service\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"L\n\x0b\x43hatRequest\x12)\n\x08messages\x18\x01 \x03(\x0b\x32\x17.ai_service.ChatMessage\x12\x12\n\nproject_id\x18\x02 \x01(\t\"\x1f\n\x0c\x43hatResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"&\n\x13HealthCheckResponse\x12\x0f\n\x07isAlive\x18\x01 \x01(\x08\x32\x89\x01\n\tAIService\x12\x39\n\x04\x43hat\x12\x17.ai_service.ChatRequest\x1a\x18.ai_service.ChatResponse\x12\x41\n\x0bHealthCheck\x12\x11.ai_service.Empty\x1a\x1f.ai_service.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHATMESSAGE']._serialized_start=32
  _globals['_CHATMESSAGE']._serialized_end=76
  _globals['_CHATREQUEST']._serialized_start=78
  _globals['_CHATREQUEST']._serialized_end=154
  _globals['_CHATRESPONSE']._serialized_start=156
  _globals['_CHATRESPONSE']._serialized_end=187
  _globals['_EMPTY']._serialized_start=189
  _globals['_EMPTY']._serialized_end=196
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=198
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=236
  _globals['_AISERVICE']._serialized_start=239
  _globals['_AISERVICE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
